### ISSUE TITLE
Erlang Record False Negative

### ISSUE THREAD

**Issue by albsch** [etylizer/etylizer#138]
Records seem to not catch some errors:

```erlang
-record(bar, { some_atom :: atom(), some_list :: list() }).

-spec foo(atom()) -> #bar{}.
foo(Input) ->
    #bar{some_atom = Input, some_list = {this,is,a,tuple}}.
```

This passes currently without detecting that `some_list` is assigned a tuple. 

Test case from the Dialyzer test suite as `should fail`.

**Comment by skogsbaer** [comment]
This is expected as with inference, you get the following type:

```
{foo/1 => FORALL $1 . fun(($1) -> {bar, $1, {this, is, a, tuple}})}
```

which corresponds to the following spec:

```
-spec foo(T) -> #bar{ some_atom :: T, some_list :: {this, is, a, tuple} }.
```

If you add this spec

```erlang
-spec foo(#bar{}) -> #bar{}.
```

typechecking fails as expected.

**Comment by albsch** [comment]
Sorry, I failed to copy the type spec for the test case. Edited the example.
