### ISSUE TITLE
top-level type alias causes type checking to fail

### ISSUE THREAD

**Issue by skogsbaer** [etylizer/etylizer#157]
In branch `sw/case-study`, there is a file `test_files/etylizer-mini/src/test.erl` which has very strange behavior:

If you type check this file in its own project, type checking fails:

```
$ cd test_files/etylizer-mini/
$ ./check.sh --no-deps src/test.erl
Checking src/test.erl
src/test.erl:35:18: Type error: expression failed to type check
%   35|         error -> Map#{ Key => Val}
%     |
```

If you edit `test_files/etylizer-mini/src/test.erl`  to use the second type spec (which just expands the type alias `t1`, type checking succeeds.

Very strangely, if you copy `test_files/etylizer-mini/src/test.erl` to the toplevel dir of the project, then the file type checks for both specs:

```
$ cp test_files/etylizer-mini/src/test.erl .
$ ./ety --force test.erl
```

**Comment by skogsbaer** [comment]
@albsch this is the strange bug I've mentioned in the meeting.

**Comment by skogsbaer** [comment]
I hoped this could be fixed by #158 but this is not the case. The bug is still present with #158

**Comment by albsch** [comment]
With this command:

>  ../../ety --build --force -P . -I src -l debug --no-deps src/test.erl

type checking fails, but with this

>  ../../ety --build --force -P . -I src -l debug src/test.erl

It succeeds. What does `--no-deps` do exactly?

**Comment by skogsbaer** [comment]
With `--no-deps`, the dependencies of test.erl (i.e. the modules imported by test.erl from the same project) are not type checked. This should not matter here because test.erl does not import anything from the same project. But indeed, it does.

**Comment by albsch** [comment]
Smaller module which exhibits the same behavior:

```erlang
-module(test).
-compile(export_all).
-type t1(K, V) :: #{ K => V }.
-spec insert(t1(K, V)) -> #{K => V}.
insert(Map) -> Map.
```

**Comment by albsch** [comment]
The constraints generated are slightly different, order and variable naming. Most likely some internal conversion issue with variable names and still a caching issue left, let me check.

```erlang
Fails:
[{scsubty, 15:20, $8, #{K => V}},
 {scsubty, 16:21, $14, #{K => V}},
 {scsubty, 15:9, $0 /\ {ok, any()}, {$4, $5}},
 {scsubty, 15:20, #{$9 => $10}, $8},
 {scsubty, 14:10, $3, $0},
 {scsubty,
  14:10,
  fun(('K'@1 /\ any(), #{'K'@1 /\ any() => 'V'@0 /\ any()}) -> {ok,
                                                                'V'@0 /\ any()} |
                                                               error),
  fun(($2, $1) -> $3)},
 {scsubty, 14:25, user_t_08(K, V), $1},
 {scsubty, 14:5, $0, {ok, any()} | error},
 {scsubty, 16:21, #{$15 => $16}, $14},
 {scsubty, 16:30, V, $16},
 {scsubty, 16:23, K, $15},
 {scsubty, 15:9, $0 /\ {ok, any()}, {$6, $7}},
 {scsubty, 14:20, K, $2},
 {scsubty, 16:18, user_t_08(K, V), #{$15 => $16}}]

OK
[{scsubty,
  14:10,
  fun(('K'@0 /\ any(), #{'K'@0 /\ any() => 'V'@1 /\ any()}) -> {ok,
                                                                'V'@1 /\ any()} |
                                                               error),
  fun(($2, $1) -> $3)},
 {scsubty, 15:20, $8, #{K => V}},
 {scsubty, 16:21, $14, #{K => V}},
 {scsubty, 15:9, $0 /\ {ok, any()}, {$4, $5}},
 {scsubty, 15:20, #{$9 => $10}, $8},
 {scsubty, 14:10, $3, $0},
 {scsubty, 14:25, user_t_08(K, V), $1},
 {scsubty, 14:5, $0, {ok, any()} | error},
 {scsubty, 16:21, #{$15 => $16}, $14},
 {scsubty, 16:30, V, $16},
 {scsubty, 16:23, K, $15},
 {scsubty, 15:9, $0 /\ {ok, any()}, {$6, $7}},
 {scsubty, 14:20, K, $2},
 {scsubty, 16:18, user_t_08(K, V), #{$15 => $16}}]
```

**Comment by albsch** [comment]
The symbolic table is different for these invocation:

```erlang
#{{ref,user_t_08,2} => {ty_scheme, [{'V',{predef,any}},{'K',{predef,any}}], {map,[{map_field_opt,{var,'K'},{var,'V'}}]}}}
#{{ref,user_t_08,2} => {ty_scheme, [{'K',{predef,any}},{'V',{predef,any}}], {map,[{map_field_opt,{var,'K'},{var,'V'}}]}}},
```

I wrongly assumed the order is defined for a type scheme, i.e. is the same order of the user type definition. That's not the case.

**Comment by albsch** [comment]
I wrongly assumed the order of a type scheme is defined (i.e. the same as the argument order of `-type t1`) and combined them in the substitution naively like this:

```erlang
Map = subst:from_list(lists:zip([V || {V, _Bound} <- Vars], Args)),
```

When the order switches, the resulting substitution will then be wrong:

```erlang
{map,[{map_field_opt,{var,'V'},{var,'K'}}]}
```

**Comment by albsch** [comment]
If I have a named type `t1`

```erlang
{named, {ref,t1,2},  [ Arg1 , Arg2 ]}
```

and an entry in the symbol table

```erlang
{ref,t1,2} =>
  {ty_scheme, [{'V',{predef,any}},{'K',{predef,any}}], {map,[{map_field_opt,{var,'K'},{var,'V'}}]}}
```

How do I know if `Arg1` should be substituted via `V` or via `K` @skogsbaer ?

**Comment by skogsbaer** [comment]
@albsch Your approach is correct. The variable ordering in a type scheme is relevant, at least when it is used as the right-hand side of a type definition. I guess the bug is in ast_transform. I will have a look.

**Comment by skogsbaer** [comment]
Here's a fix: https://github.com/etylizer/etylizer/pull/159
