### ISSUE TITLE
Memoization accross different test runs

### ISSUE THREAD

**Issue by skogsbaer** [etylizer/etylizer#40]
See #13 

- Why does it get slower after executing multiple tests?
- Wouldn't it be better the reset the cache before running a test?

**Comment by albsch** [comment]
After initial investigation it's not related to executing multiple tests after another nor is it related to the (tally) caching mechanism.
Deleting all other tests, running `rebar3 eunit -m typing_test` results in a significantly slower test `case_10_fail` than running `ety --build --force test_files/tycheck_simple.erl -o case_10_fail`.

**Comment by albsch** [comment]
There is actually an issue with sharing, but also an issue of determinism. Changing the order of the constraints can vary the processing time up to x20 after quick investigation. This will be tracked separately in #43.

**Comment by skogsbaer** [comment]
Should this be closed, now that we have #43?

**Comment by albsch** [comment]
This will be closed automatically by Github after #42 is merged because it's linked.
