### ISSUE TITLE
Test case slow, but fast on cmdline

### ISSUE THREAD

**Issue by skogsbaer** [etylizer/etylizer#54]
The following two tests (branch sw/error-msgs) cause a timeout when run as unit tests. But when invoked on the cmdline, they perform fast. See PR #38, file `test/error_msgs_tests.erl`

~~~erlang
-module(invalid_map).

-compile(export_all).
-compile(nowarn_export_all).

-spec bar(atom()) -> integer().
bar(_) -> 0.

-spec foo([integer()]) -> [integer()].
foo(L) -> lists:map(fun bar/1, L).
~~~

~~~erlang
-module(redundant_branch).

-compile(export_all).
-compile(nowarn_export_all).

-spec bar(integer()) -> a | b |c .
bar(_) -> a.

-spec foo(a | b | c) -> integer().
foo(X) ->
    case bar(X) of
        a -> 1;
        b -> 2;
        c -> 3
    end.
~~~

**Comment by skogsbaer** [comment]
`list_pattern_02` is also a test case that is fast on cmdline but sometimes timeouts in CI

**Comment by skogsbaer** [comment]
`list_pattern_07` is also slow (tally ~7s).

**Comment by skogsbaer** [comment]
Both example take about 3s on the cmdline. That's not really fast.

**Comment by albsch** [comment]
Not relevant anymore. Closing until another example exhibits this behavior with the current branch.
