### ISSUE TITLE
rebar3 Plugin

### ISSUE THREAD

**Issue by mpope9** [etylizer/etylizer#91]
Hi!

I think this tool is very interesting. I've created a rebar3 plugin here https://github.com/mpope9/rebar3_etylizer, which can be easily published to hex for more broad use. I am not going to publish it. Here is an example usage:

```
> rebar3 etylizer
Checking src/my_file.erl
===> etylizer: named references not implemented yet
===> etylizer failure dectected
```

Two configs are supported right now: `src_paths` and `project_root`, I've set them to default to `src/` and `.`, which makes this work out of the box for most rebar3 projects.

Let me know if you want me to transfer ownership of the repo to this org or just fold it into the source or keep it separate for now.

**Comment by albsch** [comment]
Wow, thank you for this contribution! It seems like a valuable contribution to the project and we could possibly transfer the ownership of the repo to this org. Since I myself have no extensive experience in maintaining a rebar3 plugin, I'll be happy to discuss this with the other members of the project.

**Comment by mpope9** [comment]
🙌 Great, I'll keep an eye on this issue for more details.

**Comment by mpope9** [comment]
@albsch any interest in the ownership transfer for this?

**Comment by albsch** [comment]
Sorry for the late response. Yes, we can transfer the ownership. @edgardSchi will take a look at it.

**Comment by edgardSchi** [comment]
Thank you again @mpope9 for the plugin. We are happy to take the ownership of the repo if you transfer it to this organization.

**Comment by mpope9** [comment]
@albsch @edgardSchi Sorry for the late reply. Sounds good!

**Comment by mpope9** [comment]
@edgardSchi I tried to transfer ownership but got this error:
```
You don’t have the permission to create public repositories on etylizer
```

Should I transfer it to you first?

**Comment by albsch** [comment]
@mpope9 I think you should be able to transfer it now.

**Comment by mpope9** [comment]
Great thanks! I will be available to make changes if needed.
