### ISSUE TITLE
Possible to SANITY etally:sanity_substitution/3?

### ISSUE THREAD

**Issue by mpope9** [etylizer/etylizer#93]
Taking into account the changes here: https://github.com/etylizer/etylizer/pull/92, the next biggest offender that I've found is the function `etally:sanity_substitution/3`. Is it possible to wrap this in a SANITY macro or is it a runtime requirement?

This reduces time to analyze the module that I referenced in the previous PR from ~6.5-7 seconds to ~4.2-5 seconds, which is a pretty good reduction.

**Comment by albsch** [comment]
One should definitely wrap this in a `?SANITY` macro.
